version: "3.8"

services:
  # Infra services
  mysql-server:
    image: mysql
    networks:
      - kiwi_payment_network
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p1234']
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    depends_on:
      - kafka-1

  myredis:
    image: redis
    networks:
      - kiwi_payment_network
    hostname: myredis
    ports:
      - "6379:6379"

  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kiwi_payment_network
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:latest
    networks:
      - kiwi_payment_network
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

  kafka-2:
    image: confluentinc/cp-kafka:latest
    networks:
      - kiwi_payment_network
    ports:
      - '9093:9093'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

  kafka-3:
    image: confluentinc/cp-kafka:latest
    networks:
      - kiwi_payment_network
    ports:
      - '9094:9094'
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29094,EXTERNAL://localhost:9094
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    image: provectuslabs/kafka-ui
    networks:
      - kiwi_payment_network
    container_name: kafka-ui
    ports:
      - "8989:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:29092,kafka-2:29093,kafka-3:29094
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1:32181
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kafka-3

# Domain services
  order-service:
    image: order-service
    networks:
      - kiwi_payment_network
    ports:
      - "8080:8080"
    depends_on:
      mysql-server:
        condition: service_healthy

  catalog-service:
    image: catalog-service
    networks:
      - kiwi_payment_network
    ports:
      - "8081:8081"
    depends_on:
      mysql-server:
        condition: service_healthy

  wallet-service:
    image: wallet-service
    networks:
      - kiwi_payment_network
    ports:
      - "8082:8082"
    depends_on:
      mysql-server:
        condition: service_healthy

  seller-service:
    image: seller-service
    networks:
      - kiwi_payment_network
    ports:
      - "8083:8083"
    depends_on:
      mysql-server:
        condition: service_healthy

  hot-catalog-service:
    image: hot-catalog-service
    networks:
      - kiwi_payment_network
    ports:
      - "8084:8084"
    depends_on:
      mysql-server:
        condition: service_healthy

  catalog-review-service:
    image: catalog-review-service
    networks:
      - kiwi_payment_network
    ports:
      - "8085:8085"
    depends_on:
      mysql-server:
        condition: service_healthy

  catalog-like-service:
    image: catalog-like-service
    networks:
      - kiwi_payment_network
    ports:
      - "8086:8086"
    depends_on:
      mysql-server:
        condition: service_healthy

  order-query-service:
    image: order-query-service
    networks:
      - kiwi_payment_network
    ports:
      - "8087:8087"
    depends_on:
      mysql-server:
        condition: service_healthy

networks:
  kiwi_payment_network:
    driver: bridge