version: '3'
services:
  axon-server:
    container_name: axon-server
#    image: axoniq/axonserver:4.6.3-jdk-11-dev
    image: axoniq/axonserver:4.6.4-jdk-17-dev
    networks:
      - syh_network
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
#      - C:\Users\syh80\workspace\docker-volume\axonserver\axoniqaxonserver4.6.3-jdk-11-dev\data:/axonserver/data
#      - C:\Users\syh80\workspace\docker-volume\axonserver\axoniqaxonserver4.6.3-jdk-11-dev\events:/axonserver/events
#      - C:\Users\syh80\workspace\docker-volume\axonserver\axoniqaxonserver4.6.3-jdk-11-dev\config:/axonserver/config:ro

      - C:\Users\syh80\workspace\docker-volume\axonserver\axoniqaxonserver4.6.4-jdk-17-dev\data:/axonserver/data
      - C:\Users\syh80\workspace\docker-volume\axonserver\axoniqaxonserver4.6.4-jdk-17-dev\events:/axonserver/events
      - C:\Users\syh80\workspace\docker-volume\axonserver\axoniqaxonserver4.6.4-jdk-17-dev\config:/axonserver/config:ro
  #      - axonserver-data:/axonserver/data
  #      - axonserver-events:/axonserver/events
  #      - axonserver-config:/axonserver/config:ro
  mysql:
    #    image: mysql:8.0
    image: mysql
    networks:
      - syh_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      #      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - C:\Users\syh80\workspace\docker-volume\mysql_docker\mysql-container:/var/lib/mysql
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234

  zookeeper:
    image: bitnami/zookeeper:latest
    networks:
      - syh_network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_TLS_CLIENT_AUTH=none
      - ZOO_TLS_QUORUM_CLIENT_AUTH=none

  kafka:
    image: bitnami/kafka:latest
    networks:
      - syh_network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=LC://kafka:29092,LX://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LC:PLAINTEXT,LX:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LC
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    networks:
      - syh_network
    ports:
      - "8989:8080"
    restart: always
    depends_on:
      - kafka
      - zookeeper
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/data
  axonserver-events:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/events
  axonserver-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/axon-server-se/config

networks:
  syh_network:
    driver: bridge