spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/payment_msa_v2_order
#    url: jdbc:mysql://mysql-server:3306/payment_msa
    username: root
    password: 1234
  jpa:
    show-sql: true # 콘솔로그로 출력하려면
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 1000
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
#    consumer:
#      group-id: wallet-service
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      enable-auto-commit: false

logging:
  level:
    org.hibernate.SQL: debug # logger에 출력하려면
    org.hibernate.type.descriptor.sql: trace # 파라미터 값 출력